### PR TITLE
feat: orient walk around job/coordinator server paradigm

### PR DESCRIPTION
**Pull request by b5**

### CODE REVIEW

**Comment by Mr0grog** [comment]
The Makefile is missing a new dependency on this branch: `github.com/qri-io/ioes`. I had to add that to get it to build.

**Comment by Mr0grog** [comment]
Haven’t really dug through the code any more than was required to make it run, and here are a few things I noticed on a first go round:

- This is probably not a new problem, but if the seed URL never responds, Walk gets stuck and just hangs waiting for the response (I was trying `data together.org`). Hitting `ctrl+c` nets me a nice message:

    ```
    INFO[0219] ************************************************************************
    INFO[0219]   received kill signal. stopping & writing file
    INFO[0219]   0 urls remain in the queue
    INFO[0219]   press ^C again to exit
    INFO[0219] ************************************************************************
    INFO[0219] finalizing: SITEMAP
    INFO[0219] sitemap: finalizing
    ```

    …but then it still hangs endlessly after that.

- I ran it against `envirodatagov.org` since that’s not too big a site. I was surprised to get a lot of repeat requests (or at least they logged repeatedly). The seed (`http://envirodatagov.org`) was requested 11 times, `http://envirodatagov.org/xmlrpc.php` 3 times, and 91 other URLs each got requested twice (out of a total of 496 URLs).

- The seed was `https://` but all the logged URLs were `http://`. That probably came from some normalizing that happened somewhere, but not sure what URLs actually got requested. We should make sure it requested `https://` and that it logs what it requested.

- At one point, it requested:

    ```
    [404] GET http://envirodatagov.org/website-monitoring/tracking-team
    ```

    Which the sitemap tells me came from:

    ```
    http://envirodatagov.org/the-overhaul-of-epa-gov-has-already-begun
    ```

    I was surprised about that 404, so I went to check it and discovered:
    - The actual link was to `https://envirodatagov.org/website-monitoring/tracking-team/` (trailing slash and `https`)
    - Not having the trailing slash is a 404. So it seems like we wound up normalizing the URL before requesting, and requesting the normalized URL instead of the actual linked URL. I’m thinking maybe we aren’t separating the URL to be requested in the queue from the normalized URL key it’s being stored under. Need to check (again, haven’t dug through the code on this PR yet).

- After the sitemap writes, it hangs and never quits. (Maybe what was happening after hitting `ctrl+c` above in my first bullet; I had thought it was just stuck on the HTTP request that was hanging.)

- For redirects, I’m getting entries like:

    ```json
    {
      "http://envirodatagov.org?p=932": {
        "url": "http://envirodatagov.org?p=932",
        "title": "",
        "timestamp": "2019-05-17T16:18:07.764401-07:00",
        "status": 301
      }
    }
    ```

    That don’t tell me the target of the redirect (`http://envirodatagov.org/publication/public-protections-under-threat` in this case).


For context, my configs:

**Config**

```json
{
  "Queue": {
      "Type": "local"
  },
  "RequestStore": {
      "Type": "local"
  },
  "Badger": {
    "Dir": "badger",
    "ValueDir": "badger",
    "ValueLogFileSize": 1073741823,
    "DoNotCompact":        false,
    "LevelOneSize":        268435456,
    "LevelSizeMultiplier": 10,
    "TableLoadingMode":    1,
    "ValueLogLoadingMode": 2,

    "MaxLevels":               7,
    "MaxTableSize":            67108864,
    "NumCompactors":           3,
    "NumLevelZeroTables":      5,
    "NumLevelZeroTablesStall": 10,
    "NumMemtables":            5,
    "SyncWrites":              true,
    "NumVersionsToKeep":       1,

    "ValueLogMaxEntries": 1000000,
    "ValueThreshold":     32,
    "Truncate":           false
  },
  "UnfetchedScanFreqMilliseconds": 0
}
```

**Job**

```json
{
  "Seeds": [
    "https://envirodatagov.org"
  ],
  "SeedsPath": "",
  "Crawl": true,
  "Domains": [
    "https://envirodatagov.org"
  ],
  "IgnorePatterns": null,
  "DoneScanMilli": 10000,
  "DelayMilli": 0,
  "StopAfterEntries": 0,
  "StopURL": "",
  "BackoffResponseCodes": null,
  "MaxAttempts": 3,
  "Workers": [
    {
      "Parallelism": 10,
      "Type": "local",
      "DelayMilli": 500,
      "Polite": true,
      "RecordResponseHeaders": false,
      "RecordRedirects": true,
      "UserAgent": ""
    }
  ],
  "ResourceHandlers": [
    {
      "Type": "sitemap",
      "SrcPath": "",
      "DstPath": "sitemap.json",
      "Prefix": ""
    }
  ]
}
```

Ran with `walk start --job config.job.json`

**Comment by Mr0grog** [comment]
Subsequent runs have the same slightly-confusing-what’s-happening-because-it’s-resuming-from-the-existing-badger-db problem you ran into in the demo a few weeks back. Is resuming that way intentional, or just an effect of Badger serializing to disk?

Being able to resume a half-done job after a crash is 💯, but a little confusing when the previous job finished successfully. Maybe something needs to drop the appropriate parts of the DB after all the handlers finish?

**Comment by b5** [comment]
ok we talked, I'm going to merge this and create issues out of the stuff @Mr0grog has pointed out!

**Pull request merged**
